<?php

require_once dirname(__FILE__) . '/../../src/StringCalculator.php';

/**
 * Test class for StringCalculator.
 * Generated by PHPUnit on 2013-01-13 at 19:20:49.
 */
class StringCalculatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var StringCalculator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new StringCalculator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
